# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

title: LAB
description: >- # this means to ignore newlines until "baseurl:"
  Bay is a minimal Jekyll Theme.
baseurl: "" # the subpath of the site
url: "https://johg15.github.io" # the base hostname & protocol for the site
og_image: /assets/img/profile-pic.jpg
google_analytics: "UA-121636368-3"

header:
  pages:
    - name: Home
      slug: /
#    - name: Work
#    - name: Blog
    - name: People
    - name: Research
    - name: Publications

footer:
  show_powered_by: false
  contact:
    - name: Email
      value: hygijo@jbnu(dot)ac(dot)kr
      link: mailto:hygijo@jbnu.ac.kr
#    - name: WeChat
#      value: YourWeChatUsername
#      link: "#"
  follow:
#    - name: Twitter
#      link: http://twitter.com/YourTwitterUsername
#      username: "@YourTwitterUsername"
#    - name: Facebook
#      link: http://facebook.com/YourFacebookUsername
    - name: LinkedIn
      link: https://www.linkedin.com/in/hygijo
    - name: GitHub
      link: http://github.com/johg15
#    - name: Dribbble
#      link: https://dribbble.com/YourDribbbleUsername
#    - name: RSS
#      link: /feed.xml
    - name: GoogleScholar
      link: https://scholar.google.com/citations?user=S36EOoMAAAAJ&hl=ko

# Build settings
markdown: kramdown
sass:
    style: :compressed
plugins:
  - jekyll-feed

# Excluded items
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - feed.xml
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Used for defeating caching
version: 1
